config/locales/en.yml
Addition : mention the site was deployed by Open Source Politics
"Website made by Open Source Politics with the Decidim free software"
=> Update footer string made with open source

Gemfile, Gemfile.lock, config/initializers/decidim_questions.rb
Remove gems "captcha", "url-aliases" from gemfile so we have a usable master to boot instances.
=> Remove gems : captcha, url-aliases

Gemfile, config/initializers/decidim.rb, config/secrets.yml, spec/system/decidim/authentication_spec.rb
The PR is modeled after this PR : https://gitlab.com/open-source-politics/deploy/gnchr/osp-app/-/merge_requests/2/diffs
=> Set up geocoder config for french addresses

Gemfile, Gemfile.lock, config/initializers/omniauth_publik.rb, config/secrets.yml, spec/system/sso/omniauth_publik_spec.rb
Allow instances to configure Publik SSO
=> Feature omniauth publik

app/controllers/decidim/proposals/proposals_controller.rb, app/models/decidim/proposals/proposal.rb, spec/controllers/decidim/proposals/proposals_controller_spec.rb
=> Fix proposals permissions 0.24

OVERLOADS.md, app/cells/decidim/proposals/proposal_m_cell.rb, app/controllers/decidim/proposals/proposals_controller.rb, app/models/decidim/proposals/proposal.rb, config/environments/production.rb, config/i18n-tasks.yml, config/initializers/rack_attack.rb, spec/controllers/decidim/proposals/proposals_controller_spec.rb
* Rack attack initializer
* St log level to info
Co-authored-by: Armand Fardeau <fardeauarmand@gmail.com>
=> Merge develop and master branches

config/initializers/devise.rb, spec/system/locales_spec.rb
backport from [this pr](https://github.com/decidim/decidim/pull/9025)
=> fix devise locales

public/robots.txt
=> Do not index public profiles with robots.txt 0.24

config/initializers/extends.rb, lib/extends/controllers/decidim/devise/sessions_controller_extends.rb, spec/controllers/sessions_controller_spec.rb
=> Extends Session controller and skip AH

config/initializers/extends.rb, lib/extends/controllers/decidim/devise/sessions_controller_extends.rb, spec/controllers/sessions_controller_spec.rb
Allow to skip AH step on first login
=> Extends Session controller and skip AH (#95)

Gemfile, Gemfile.lock
=> Merge develop on master 

config/sidekiq.yml
We should update the queues order in Sidekiq configuration
Order is : Most important to less important
=> Update sidekiq queues order

config/sidekiq.yml
* Update sidekiq queues order
* Increase backups queue
=> Update sidekiq queues order (#116)

config/sidekiq.yml
There is missing queues for exports and translation
=> Add missings queues in Sidekiq config

.github/workflows/tests.yml, app/helpers/application_helper.rb
=> Update Gh Actions workflow

.gitignore, .idea/.gitignore, Gemfile.lock, config/initializers/decidim.rb, package-lock.json, packages/browserslist-config/package.json, packages/core/package.json, packages/dev/package.json, packages/elections/package.json, packages/eslint-config/package.json, packages/stylelint-config/package.json, packages/webpacker/package.json, spec/spec_helper.rb, yarn.lock
Allow system administrators to enable all locales in Decidim
1. Create a new app and seed (seeds will take a moment because it generates translation for each available locale)
2. See available locales in app
3. Create a new organization and select some locales
4. See difference between the two organizations
=> [Feature] - Allow all locales 

OVERLOADS.md, app/controllers/decidim/proposals/collaborative_drafts_controller.rb, app/views/decidim/proposals/collaborative_drafts/_wizard_aside.html.erb, app/views/v0.26/decidim/proposals/collaborative_drafts/_show.html.erb, spec/system/collaborative_drafts_fields_spec.rb
=> Fix collaborative drafts

OVERLOADS.md, app/controllers/decidim/budgets/projects_controller.rb, spec/system/sorting_projects_spec.rb
Fix "Order by most voted" budgets
=> Backport sort of budgets

Gemfile, Gemfile.lock, README.md, db/migrate/20221026132636_add_assistant_to_organization.decidim_ludens.rb, db/migrate/20221026132637_create_decidim_participative_actions.decidim_ludens.rb, db/migrate/20221026132638_add_decidim_organization_references_to_decidim_participative_action.decidim_ludens.rb, db/migrate/20221026132639_add_documentation_to_decidim_participative_actions.decidim_ludens.rb, db/migrate/20221026132640_add_enable_ludens_to_organization.decidim_ludens.rb, db/schema.rb, lib/tasks/decidim_app.rake, package-lock.json, package.json, yarn.lock
Add gem ludens
Add migrations
initialize module
Update setup task and readme
=> add ludens

app/api/deployment_type.rb, app/api/query_extensions.rb, config/application.rb, config/initializers/decidim_api.rb
Displays deployment information in graphql editor
=> Display commit with graphql

app/views/layouts/decidim/_head_extra.html.erb, config/initializers/sentry.rb, lib/initializers/sentry_setup.rb, spec/lib/sentry_setup_spec.rb
=> Extract Sentry setup to a proper class

.github/workflows/tests.yml, lib/decidim/assets_hash.rb, lib/tasks/test.rake
=> Add assets cache

config/i18n-tasks.yml
=> Fix i18n-tasks

lib/decidim/assets_hash.rb, spec/lib/assets_hash_spec.rb
=> Fix assets hash

spec/commands/decidim/budgets/admin/create_order_reminders_spec.rb
Fixs the test about order reminders
=> fix flaky on order reminders

app/views/layouts/decidim/_head_extra.html.erb, spec/lib/importers/import_manifest_spec.rb
This PR fix the infinite loading when completing a proposal with awesome custom fields
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=7606b488c3fc4986a954ab5cdf57ed33&p=d1f4388e202847e1962e95a31f02fcc9&pm=c)
Example:
* Go to awesome config, custom fields
* Add a custom field on processes
* Go to processes
* Try creating a proposal
* See your custom fields
=> fix awesome js tags

OVERLOADS.md, config/initializers/extends.rb, lib/extends/cells/decidim/content_blocks/hero_cell_extends.rb
Add bckground image to cache.
- Related to https://github.com/decidim/decidim/pull/9471
- [Notion card](https://www.notion.so/opensourcepolitics/Probl-me-d-int-gration-de-photo-page-d-accueil-8f892eddf7614582b288558ce32f70ad)
* Go to homepage settings
* Upload new image to hero content block
* Refresh homepage
=> Fix hero cell cache

.github/workflows/tests.yml, lib/decidim/assets_hash.rb, spec/lib/assets_hash_spec.rb
=> Output artifacts

.env-example, config/initializers/decidim.rb
Set up default locale as env var.
=> Set default locale as env var

.github/workflows/tests.yml, .gitignore, .simplecov, README.md, lib/decidim/assets_hash.rb, lib/decidim/rspec_runner.rb, lib/tasks/db.rake, lib/tasks/decidim_app.rake, lib/tasks/import.rake, lib/tasks/repair_data.rake, lib/tasks/restore_dump.rake, lib/tasks/test.rake, spec/lib/assets_hash_spec.rb, spec/lib/rspec_runner_spec.rb
I found that we were not using code coverage and this is a mistake, due to the nature of the parallelization of the runners it was impossible to upload the reports correctly.
I added an output that aggregates the reports in order to use the appropriate coverage tools and improve the code quality
=> Fix coverage

Gemfile, Gemfile.lock
Add decidim-module-cache_cleaner
- [Notion card](https://www.notion.so/opensourcepolitics/Angers-Cache-proposals-577ec12035994473962c54773e8a6f75?pvs=4)
* Log in as an admin
* Go to the admin panel
* Go to the "Cache Cleaner" section
* Click on the "Clean cache" button
* Wait for the cache to be cleaned
* Enjoy your clean cache
=> Add decidim-cache_cleaner

config/secrets.yml
Add these 3 environment variables : 
- `SMTP_PORT`
- `SMTP_STARTTLS_AUTO`
- `SMTP_AUTHENTICATION`
=> Add missing SMTP env vars

config/environments/development.rb, config/environments/production.rb
Set global id expiration to 100 years
- Fixes https://github.com/decidim/decidim/issues/10609
- [Notion card](https://www.notion.so/opensourcepolitics/Cap-Digital-Erreur-serveur-lors-de-la-mod-ration-de-contenu-cb1e25b9a6f74e168043767941e225ab?pvs=4)
=> Set global id expiration

app/api/deployment_type.rb, config/application.rb, spec/types/deployement_type_spec.rb
Add remote url in API deployment query
=> Add remote in api

Gemfile, Gemfile.lock, config/initializers/health_check.rb, config/initializers/sidekiq_alive.rb
Add heathchecks for K8s deployments
=> Add healthchecks

Gemfile, Gemfile.lock
Pin sidekiq
- [Notion card](https://www.notion.so/opensourcepolitics/CESE-Sidekiq-mail-7ae4e69ddb864b2db596d80911290100?pvs=4)
=> Pin sidekiq

Gemfile.lock
=> Bump interactive maps

config/participative_actions.yaml
Module Decidim Ludens can't find participative actions file from library
- Related to https://github.com/OpenSourcePolitics/decidim-ludens/issues/57
=> HOTFIX - Add missing participative_actions.yaml

Gemfile.lock
=> Fix bundler version

Gemfile.lock, config/participative_actions.yaml
=> Bump decidim-app master

config/sidekiq.yml
=> Fix scheduler key

Gemfile
Fix a problem where the dot env was not loaded correctly, by loading it this way we make sure that it is always loaded at the beginning
https://github.com/bkeepers/dotenv#note-on-load-order
=> Fix dotenv loading

.github/workflows/ci_cd.yml, spec/system/locales_spec.rb
Enforced locales should be fr and en only
=> Fix CI/CD enforced locales

config/sidekiq.yml
To avoid spamming the containers as a service we will randomly start the services between 6:00 and 9:00
=> Fix scheduling

config/sidekiq.yml
=> Remove scheduled tasks cleaner

lib/decidim/admin_creator.rb, lib/decidim/system_admin_creator.rb
Allows tasks to be run twice (discriminant email)
=> Make task idempotent

.github/workflows/ci_cd.yml
Add pull request trigger to start ci when coming from a pull request
=> Add pull request trigger

config/i18n-tasks.yml, config/locales/fr.yml
We have a missing french translation in BO
=> Add missing BO translation for admin accountability

config/environments/production.rb, docker-compose.yml
Avoid compatibility issue when running in k8s mode
=> Use memcached store in production

lib/decidim_app/k8s/secondary_hosts_checker.rb, spec/lib/decidim_app/k8s/secondary_hosts_checker_spec.rb
When we were using the secondary host system, there was a case where we were redirected to an address containing https. To get around this problem, we transform the URL into an object that we can query at the end and return the real host.
=> Fix secondary hosts checker

lib/tasks/decidim_app.rake
=> Add install hook

lib/decidim_app/k8s/commands/organization.rb, lib/decidim_app/k8s/configuration.rb, spec/fixtures/k8s_configuration_example.yml, spec/lib/decidim_app/k8s/commands/organization_spec.rb, spec/lib/decidim_app/k8s/configuration_spec.rb
Fix organization update by using a matching system to find the appropriate transformation
=> Fix organization update

lib/decidim_app/k8s/secondary_hosts_checker.rb, spec/lib/decidim_app/k8s/secondary_hosts_checker_spec.rb
We don't need to check for the HTTPS, we only care about the DNS resolution
=> Replace HTTPS tests with HTTP

.github/workflows/ci_cd.yml, app/services/decidim/repair_nickname_service.rb, spec/services/decidim/repair_nickname_service_spec.rb
=> Fix invalid users

lib/decidim_app/k8s/organization_exporter.rb, spec/lib/decidim_app/k8s/organization_exporter_spec.rb
Fix export of smtp settings when nil
=> Fix export when smtp settings are nil

.github/workflows/ci_cd.yml
Downgrade chromedriver temporarily
=> Downgrade chromedriver temporarily

lib/decidim_app/k8s/organization_exporter.rb, spec/lib/decidim_app/k8s/organization_exporter_spec.rb
Adding the possibility to dump external database with parameters for : 
- host
- username
- password
- port
=> Add parameters for dumping external database

lib/active_storage/migrator.rb, spec/lib/active_storage/migrator_spec.rb
=> feat: Add parallel to K8s migrator

Gemfile.lock
=> Fix interactive map wrong version

Gemfile, Gemfile.lock, app/services/decidim/repair_url_in_content_service.rb, spec/services/decidim/repair_url_in_content_service_spec.rb
Refactor RepairUrlService. This PR is a refactor but does not introduce new feature
**Product test is complicated without a corrupted database backup**
=> Ref: Fix url in content

docker-compose.yml
Add missing env vars to docker compose
=> Add missing env vars to docker compose

.github/workflows/ci_cd.yml, .github/workflows/clean_dangling_images.yml
Always upload branch image
Delete image when branch is deleted
=> Always upload image

.github/workflows/ci_cd.yml
Avoid building image twice on master
=> fix: Avoid building twice on master

Dockerfile
Solution inspired by : https://mailsnag.com/blog/optimized-ruby-dockerfile
Reduce Ram usage for sidekiq from 741.49 MiB to 436.02 MiB idle
=> feat: Reduce memory usage (introduce jemalloc)

.github/workflows/ci_cd.yml
Fail fast was not setup for system tests
=> Set fail fast to false for system tests

Dockerfile
Switch to debian based image to avoid on error on seven_zip extensions compilation
=> feat: Switch to debian based image

config/environments/production.rb, lib/decidim_app/sentry_setup.rb
* Remove healthcheck from logs
* Removes healthcheck from sentry trace
=> fix: Silence healthcheck in log and sentry

Makefile
=> refactor: update Makefile commands

Gemfile, Gemfile.lock, README.md
Bump the module to add the fix on component settings
Related to:
https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers/pull/6
go to the survey component and check that both step and global checkboxes are necessary.
=> Bump module multiple answer survey with last commit

Gemfile.lock, config/application.rb
We downgrade wicked pdf to make sure that it works correctly
- [Notion card](https://www.notion.so/opensourcepolitics/Bordeaux-Recette-P-titions-2abe3fb8be194b998699a48d39b2bab3?pvs=4)
Example:
* Go to initiatives
* Select one published and add your signature
* Export the signatures of this one
* Check if everything works correctly
=> fix: downgrade wicked_pdf

config/i18n-tasks.yml, config/locales/en.yml, config/locales/fr.yml
Add missing locales from Decidim Initiatives from Homepage.
- [Notion card](https://www.notion.so/opensourcepolitics/Bordeaux-Recette-P-titions-2abe3fb8be194b998699a48d39b2bab3?pvs=4)
Example:
* Setup your App
* Change locale to french
* Check if there is the translation
=> fix: add missing locales

.github/workflows/stale.yml
Add Github Action Workflow to close staled PR and Issues
=> feat: Add Stale bot GH workflow

.env-example, Gemfile.lock, config/secrets.yml
=> Add settings for PWA push notifications

config/i18n-tasks.yml, config/locales/en.yml, config/locales/fr.yml
Add missing translations on file upload modale
- Fixes #485 #486 
- [Notion card](https://www.notion.so/opensourcepolitics/Release-decidim-app-2-0-0-Last-minute-fixes-fed4ba0653fa4c39ad5f20589fbc3933?pvs=4)
=> fix: Add missing translations for file uploader modale

Gemfile, Gemfile.lock
Bump module Survey multiple answers module
=> hotfix: Survey multiple answers module

config/sidekiq.yml
Update cron rules for daily and weekly digests
Daily: Run at 07:00AM every day
Weekly: Run at 08:00AM on Tuesday
- Fixes #489 
- [Notion card](https://www.notion.so/opensourcepolitics/Release-decidim-app-2-0-0-Last-minute-fixes-fed4ba0653fa4c39ad5f20589fbc3933?pvs=4)
=> fix: Change cron rules

Gemfile.lock
Fix uploading image in Quill Editor JS by bumping module friendly signup
=> fix: Bump module Friendly Signup

.env-example, Gemfile, Gemfile.lock, config/initializers/decidim.rb, config/initializers/half_signup.rb, config/secrets.yml, db/migrate/20240424162056_add_main_image_to_decidim_budgets_budgets.decidim_budgets_booth.rb, db/migrate/20240424162059_add_phone_number_to_decidim_user.decidim_half_signup.rb, db/migrate/20240426092404_create_decidim_budgets_user_data.decidim_budgets_booth.rb, db/migrate/20240426092405_create_auth_settings.decidim_half_signup.rb, db/schema.rb
This PR adds few modules : 
- Budgets booth that will offer you the possibility to vote in a private space so the user cannot leave the vote phase
- Half Signup : Middleware mode that allows you to create an "half" account using your email or your phone number to make sure you can vote easily and in that mode it permits to make sure of the identity of the user each time she has to vote.
- [Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-2-2-Ajout-module-half-sign-up-acdc92c247fa42db8cd4ca2afdad7e50?pvs=4)
- Access to BackOffice
- Enable HalfSignup any method you want (may be great to test both of them individually then together)
- Go into a participatory process
- Click on categories
- Create some custom categories using the gem …
=> feat: Add multiple modules

config/i18n-tasks.yml, config/locales/en.yml, config/locales/fr.yml
Fix half signup translations for sending SMS
=> fix: Add missing SMS translation keys

Gemfile, Gemfile.lock
Bump Decidim Awesome to the last commit in order to benefit from the following fix: https://github.com/decidim-ice/decidim-module-decidim_awesome/pull/301
- Related to https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/297
Example:
* See ...
=> Fix: Bump Decidim Awesome

Gemfile.lock
=> fix: translations on module half_signup and ptp

lib/tasks/decidim_app.rake
=> fix: Marseille : Rescue DB migrate error 

lib/tasks/decidim_app.rake
=> fix: Rescue DB migrate error

Gemfile.lock
=> bump: Module Budget booth

.env-example, Gemfile.lock, app/packs/stylesheets/decidim/decidim_application.scss, app/services/decidim/sms_gateway_service.rb, app/views/decidim/budgets/line_items/update_budget.js.erb, config/i18n-tasks.yml, config/initializers/decidim.rb, config/locales/fr.yml, config/secrets.yml
When user is in budget booth, she can vote for multiple projects using button "Add your vote" or by clicking on "Read more"  and "Add to your vote" in the opened modal.
When I click on the modal's button, I expect my vote to be accepted and modal to be automatically closed.
- Related to #540 
- [Notion card](https://www.notion.so/opensourcepolitics/Marseille-Bouton-Ajouter-au-vote-c8c1367546444f24bcdaaab249d80b35?pvs=4)
Example:
* Compile JS assets `bundle exec bin/webpack`
* Access to a Participatory process from the index : http://localhost:3000/processes/
* In this PP, go to "Budgets" tab and start voting
* In the budget booth, click on "Read more" link …
=> fix: Incompatibility Category voting & Budgets booth + CSS Phone number

Gemfile.lock, app/packs/entrypoints/decidim_tc.scss, app/packs/stylesheets/decidim/decidim_application.scss, app/packs/stylesheets/decidim/modules/term_customizer.scss, app/views/decidim/term_customizer/admin/add_translations/index.html.erb, config/assets.rb, config/i18n-tasks.yml, yarn.lock
🎩 Description
Bump module_term_customizer with the FIX: The search bar in the term customizer didn't display all existing keys during a search. We increased the translation key display limit in the search bar.
📌 Related Issues
[Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-Cl-s-de-trad-ne-s-affichent-pas-dans-la-barre-de-recherche-du-Term-customizer-bbf7cd1c04d84eddb7a577832fb478b9?pvs=4)
**Testing**
- Go to admin dashboard
- Go to Term customizer
- Add a 'New translation set' with name and remove "contraint"
- Go to this new one translation set
- Click on "add multiple"
- In the search bar, search with "category" term for finding "decidim.proposals.proposals.filters.category"
=> Bump Term-Customizer

.github/workflows/ci_cd.yml
This PR downgrades chromedriver the deprecation of the unload event APIs in Chromium
- Related to [##13277 Decidim](https://github.com/decidim/decidim/pull/13277)
=> fix: Downgrade chromedriver to fix failing test

Gemfile.lock
Bump Half sign up module
- Related to https://github.com/OpenSourcePolitics/decidim-module-half_sign_up/pull/41
- [Notion card](https://www.notion.so/opensourcepolitics/Release-2-4-Am-lioration-half-sign-up-515fe5373e364b518a5bf8da5dbb410a)
=> feat: bump half_signup module

spec/system/survey_spec.rb
=> release: Marseille v2.3.0.1

Gemfile.lock
Bump of updated decidim-module-half_sign_up 
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=d7d025cf58854090adfca712c9ae29b1&pm=c)
=> bump: half_sign_up update

Gemfile.lock
Bump the module custom proposal states to have the last translations added.
- [Release 2.5 - Bump Custom proposal states](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=guillaume%40opensourcepolitics.eu&token=ixqNZ9S5lGRCj9ADpsQq#id=2586&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
Example:
* Switch to french locale
* Go to a participatory process
* Access proposals component
* Click on "États des Réponses"
* Try to create a new state
* Check that everything is translated
=> bump: Bump custom proposal states

config/locales/de.yml
Hotfix to add missing locales, won't be necessary anymore when bumped to 0.27.8+
- [odoo card](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=quentin%40opensourcepolitics.eu&token=e4gln5LDQjvnUZEEpOZm#id=3297&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
=> hotfix(locale): Add missing DE locales

Gemfile, Gemfile.lock, config/sidekiq.yml
Add block reported user task (#614)
=> release: v2.4.3

Gemfile, Gemfile.lock
Bump of the https://github.com/alecslupu-pfa/guest-meeting-registration.git module to the last commit 
- [Odoo card](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&token=vvN9fF0jkMevCkUGiz0K#id=3374&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
=> Bump: Guest meeting registration module

Gemfile.lock
Bump homepage interactive map to fix issues related to the geocoding 
- [🐛Nice - bug geolocalized scopes](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=guillaume%40opensourcepolitics.eu&token=ixqNZ9S5lGRCj9ADpsQq#id=3410&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
* Go to scopes settings
* Edit a scope
* Try to enable geolocalized
* Ensure to take a geocoding file that worked previously
* Fill the geocoding file
* Try to edit and make sure it works correctly
=> bump: Homepage Interactive Map - Geocoding Issues

app/jobs/clear_duplicated_half_signup_users_job.rb, app/jobs/concerns/decidim/logging.rb, app/jobs/decidim/papertrail_versions_job.rb, lib/tasks/clear_duplicated_users.rake, lib/tasks/db.rake, spec/jobs/clear_duplicated_half_signup_users_job_spec.rb
=> Enhance clean half signup users

.github/workflows/ci_cd.yml, Gemfile.lock
Add imagemagick to ci and update wkhtmltopdf-binary in gemfile, to fix release 2.6
=> Fix/release 2.6

Gemfile, Gemfile.lock, config/initializers/half_signup.rb, config/sidekiq.yml
=>  fix: Budget booth

Gemfile, Gemfile.lock, app/jobs/archive_users_phone_job.rb, config/initializers/half_signup.rb, config/sidekiq.yml, lib/tasks/clear_duplicated_users.rake, lib/tasks/db.rake
This release contains several bug fixes for the half sign up module.
* Add command `rake decidim:db:users:phone` to archive all phone users
=> Release 2.6.1

app/services/decidim/sms_gateway_service.rb, config/secrets.yml
=> fix: Add missing oadc in SMS GATEWAY (#664)

app/events/decidim/proposals/author_confirmation_proposal_event.rb, config/application.rb, config/locales/en.yml, config/locales/fr.yml, lib/extends/commands/decidim/proposals/publish_proposal_extends.rb, spec/commands/decidim/proposals/publish_proposal_spec.rb, spec/events/decidim/proposals/author_confirmation_proposal_event_spec.rb, spec/factories.rb
This PR is a backport of https://opensourcepolitics.odoo.com/odoo/all-tasks/4100
- [Odoo card](https://opensourcepolitics.odoo.com/odoo/all-tasks/4100)
1. After login, go to you account and then to notification settings, and check real time for "How often do you want to receive the notifications email"
2. Go to a participatory process
3. Click on proposals
4. Add a proposal
5. Publish it
6. Verify that you receive a notification and an email
7. Confirm that the text and translations in EN & FR are correct
=> Backport author notification on proposal publication

Gemfile, Gemfile.lock, config/i18n-tasks.yml, config/locales/en.yml, config/locales/fr.yml, db/migrate/20250303145032_make_sortitions_authors_polymorphic.decidim_sortitions.rb, db/migrate/20250303145033_add_commentable_counter_cache_to_sortitions.decidim_sortitions.rb, db/migrate/20250303145034_add_followable_counter_cache_to_conferences.decidim_conferences.rb, db/migrate/20250303145035_add_weight_to_conferences.decidim_conferences.rb, db/migrate/20250303145036_add_published_at_to_conference_speakers.decidim_conferences.rb, db/migrate/20250303145037_add_commentable_counter_cache_to_initiatives.decidim_initiatives.rb, db/migrate/20250303145038_add_followable_counter_cache_to_initiatives.decidim_initiatives.rb, db/migrate/20250303145039_add_field_values_and_target_to_decidim_templates.decidim_templates.rb, db/schema.rb, spec/i18n_spec.rb
Addition of the modules Initiatives, Templates and Conferences using the tag 0.29.2
* Seed you app properly
* Make sure that some initiatives has been created
* Go to initiatives settings
* Make sure you can interact with initiatives
* Access FrontOffice
* Go to initiatives page
* Try to create a new initiative
* Access BackOffice
* Go to Templates
* Try to create a new template
* Try to edit the existing one
* Make sure everything works
* Access a participatory process
* Try to create a new survey (if you tried to create a questionnaire template)
* Edit the survey and apply the new template to the survey component
* Make sure everything works correctly
* Make sure that some initiatives has been created
* Go to Conferences
* Make sure you can edit …
=> feat: Add following gems : initiatives, templates, conferences

Gemfile.lock
This PR bumps the decidim-module-extra_user_fields in develop.
- Related to https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=105547875&issue=OpenSourcePolitics%7Cdecidim-app%7C720?
=> bump: extra_user-fields

.github/workflows/ci_cd.yml, Gemfile.lock
=> release: 3.0.0

.github/workflows/ci_cd.yml, Gemfile, Gemfile.lock, app/overrides/decidim/budgets/admin/projects/index/replace_import_to_selector.html.erb.deface, config/locales/en.yml, config/locales/fr.yml, db/migrate/20250505083949_create_paper_ballot_results.decidim_budgets_paper_ballots.rb, db/schema.rb
This PR adds budgets importer and paper ballots to the decidim-app 0.27
- Run the following command to ensure Deface changes are compiled:
```
bundle exec rake deface:precompile
```
- Create a CSV file in the following format:
- `id` corresponds to the ID of the project you want to vote for.
- `paper_ballots_to_import` is the number of paper ballot votes received.
**Example CSV:**
```
id;paper_ballots_to_import
1;30
2;25
3;40
```
1. ** Prepare Projects Data:**
- Log in as an admin.
- Go to the **Backoffice**.
- Navigate to **Participatory Processes**.
- Select a **budget component** within a participatory process.
- Go to the **Projects** section.
- Click **Export** to download the current list of projects.
2. **Import Projects:**
- Use the previously exported file to try re-importing …
=> feat: Add budgets importer and paper ballots

.github/workflows/ci_cd.yml, Gemfile, Gemfile.lock, app/overrides/decidim/budgets/admin/projects/index/replace_import_to_selector.html.erb.deface, app/packs/src/decidim/data_picker.js, app/packs/stylesheets/decidim/decidim_application.scss, app/views/decidim/assemblies/assemblies/index.js.erb, app/views/decidim/participatory_processes/participatory_processes/index.js.erb, config/locales/en.yml, config/locales/fr.yml, config/locales/nl.yml, db/migrate/20250505083949_create_paper_ballot_results.decidim_budgets_paper_ballots.rb, db/schema.rb, lib/extends/controllers/decidim/devise/omniauth_registrations_controller_extends.rb, lib/tasks/repair_data.rake, spec/controllers/omniauth_registrations_controller_spec.rb
- Repair Proposals and Comments
- Bump extra user fields
- Processes index filter
- Add NL locales
- Add specs for omniauth extend
- Add budget importer
- Add paper ballots
=> release: 2.8.2

Gemfile.lock
🎩 Description
This just bumps the spam detection module to its last commit to fix the issue of usernames when the module is trying to block the user
=> bump: Spam detection to fix block_users command

.github/workflows/build_app.yml, .github/workflows/ci_cd.yml, .github/workflows/sast.yml, .github/workflows/test_app.yml, .github/workflows/zeitwerk.yml, Gemfile.lock
CI isn't running specs anymore.
This PR aims to enhance the CI process
=> ci: Fix workflows

Gemfile.lock
Remove voting instructions as it seemed not to be useful
- Related to [#19](https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=111473404&issue=OpenSourcePolitics%7Cintern-tasks%7C19)
- Access a participatory process
- Access budgets component
- Try to vote on a project
- Make sure on your first vote that the modal doesn't appear
- You can change account to make sure it works correctly
=> bump: Budgets booth

.github/workflows/ci_cd.yml
Add missing push to registry step
=> ci: Push image on release

app/cells/decidim/content_blocks/hero/show.erb, package-lock.json, yarn.lock
This PR removes forgotten `-->` on hero cell, and updates @bufbuild/protobuf package for docker img build.
Check that banner image doesn't display those symbols.
=> Fix: remove --> from hero cell

config/i18n-tasks.yml, config/locales/en.yml, config/locales/fr.yml
This PR adds 3 translation keys from header menu, for "Aide", "Rencontres" and "Activité"
- Related to https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=115439253&issue=OpenSourcePolitics%7Cdecidim-app%7C814
=> Feat: add header translation keys

Gemfile.lock
This PR bumps module decidim_budget_booth to its latest version.
Github card https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=117231824&issue=OpenSourcePolitics%7Cintern-tasks%7C53
To test the updates in last version of budget_booth:
1. In the BO, go to a process with only one budget
2. Don't define a "URL to redirect user after voting on all available budgets", but add a custom text in "Popup text after voting in all available budgets"
3. in the FO, go to the budget, add complete your vote
4. See that you are redirected to the process show page and that you have a modal with your custom text
=> feat: bump budget_booth
