app/assets/stylesheets/decidim/_email-custom.scss
app/assets/stylesheets/decidim/email.scss.erb

This PR aims to improve the way we override the Decidim email stylesheet and to put the light theme by default (header & footer in _whitish_ color).
- we overrides the `app/assets/stylesheets/decidim/email.scss` file
- this file is in fact an ERB file that will import the original file from the deployed `decidim-core` gem
- we import a local SCSS file to make it easier to edit for web developper
The result is that we always have an up to date email stylesheet from core and we can limit our code to custom styles and overrides.
> All we need to do is to edit the `app/assets/stylesheets/decidim/_email-custom.scss` file :tada: 
We simply change the header and the footer color with the one used for the main body

Refactor email stylesheet override + email light theme

---

OVERLOADS.md
app/controllers/decidim/meetings/directory/meetings_controller.rb
app/controllers/decidim/meetings/meetings_controller.rb
config/locales/en.yml
config/locales/fr.yml
spec/system/explore_meeting_directory_spec.rb
spec/system/explore_meetings_spec.rb

This PR aims to fix the meetings order for past meetings and meetings to come on our reference application. 
It also adds tests for meetings indexes and updates OVERLOAD file.

Fix meetings order 

---

OVERLOADS.md
app/views/decidim/scopes/picker.html.erb
config/locales/en.yml
config/locales/fr.yml

Monkey patch `decidim-core/app/views/decidim/scopes/picker.html.erb` and update cancel button of the sector selector modal to work like the close button.
Monkey patch no longer needed on 0.25 since webpacker

Fix display sector selection (v0.24)

---

lib/tasks/repare_data.rake
spec/lib/tasks/repare_data_spec.rb

Rake task to sanitize invalids nicknames in database.
* Seed locally a decidim-app
* Generate invalids nicknames using `bundle exec rails console`
Command to type in rails console : 
```
["Azertpoy Uiop", "Azpoer ty. Upoiop", "Azer dfy_ Uiop", ".dfsgfo.", ".azerty", "efke$fdf ^ez", ].each_with_index { |value, index| Decidim::User.new(name: "Demo #{index}", nickname: value, password: "decidim123456", password_confirmation: "decidim123456", email: "demo#{index}@example.org", organization: Decidim::Organization.first).save(validate: false) }
```
* Now execute the rake task : `bundle exec rake decidim:repare:nickname`, you should now see this output
```
I, [2022-03-23T09:46:39.785722 #2702]  INFO -- : [data:repare:nickname] :: Found 6 invalids nicknames
I, [2022-03-23T09:46:39.785848 #2702] …
```

Add repare data rake task

---

dist/robot.txt

This robot.txt will only accept visits from Googlebot, and disallow crawling on `/profiles` and `/*.pdf`.
All other bots will be disallowed

Add robot.txt example

---

Gemfile
Gemfile.lock

Unexpected text '<__truncato_root__>' is displayed on cells.

Lock Nokogiri version to '1.13.4'

---

Gemfile
Gemfile.lock

Spam detection master branch was bumped to 0.26 decidim version.
This PR aims to update the 0.25 decidim-app branch to point to 0.25 spam detection branch.

Update spam detection module branch to 0.25

---

.env-example
config/initializers/rack_attack.rb
config/locales/en.yml
config/secrets.yml
spec/lib/rack_attack_spec.rb
spec/system/confirmation_spec.rb

Bots tries to find security vulnerabilities by requesting random routes. 
I think we should consider setup `Fail2Ban` service for some requests like Wordpress, Filesystem and others
Currently, configuration will ban each IP which tries at least once to access a forbidden request for 1 hour (can be more !)

[Feature] Rack Attack setup Fail2Ban

---

config/sidekiq.yml

Hello ! I send you this PR to try to fix a bug where you had a MetricsJob failure following this message - "Day has already been taken".
I've tried to modify your Sidekiq config to make your job execute at 00:09 when it was previously at 00:00 to avoid any repetition of the following command : rake decidim:metrics:all that seemed to self-repeat and produce this error.
If this doesn't work, please tell me then i'll send you my other solution that is linked to the file that is responsible of this error which is "app/queries/decidim/comments/metrics/comments_metric_manage.rb" that we can see on the stacktrace you sent there -> 
```from decidim (5043f94d3d98) decidim-comments/app/queries/decidim/comments/metrics/comments_metric_manage.rb:23:in `block in save'
from decidim (5043f94d3d98) …
```

Fix - MetricsJob failure - Day already taken

---

lib/extends/controllers/decidim/devise/sessions_controller_extends.rb
spec/controllers/sessions_controller_spec.rb

Extends was not properly loaded therefore the first login authorization could not be skipped

Fix extends

---

Gemfile.lock

Bump friendly sign up to fix emails links
- Related to https://github.com/OpenSourcePolitics/decidim-module-friendly_signup/pull/14?
- Fixes https://github.com/OpenSourcePolitics/decidim-module-friendly_signup/issues/10?
1. Create an account
2. Go to letter opener
3. The link is redirecting to the friendly sign up confirmation page (with code)

Bump friendly sign up to fix emails links

---

.env-example
lib/initializers/sentry_setup.rb
spec/lib/sentry_setup_spec.rb

Allows to customize the sample size in the context of sidekiq in order to reduce costs and noise generated on the error tracers.
The default values are respectively 50% (web) and 10% (sidekiq) and configurable through the following environment variables: SENTRY_SAMPLE_RATE (web) and SENTRY_SIDEKIQ_SAMPLE_RATE (sidekiq)

Setup different sample rate for sidekiq

---

.github/workflows/tests.yml

When tests are failing inside a matrix job, all suite is failing.
Introducing fail-fast false allows the whole suite to run even in a failing case.

Use fail fast to continue tests on matrix if failure

---

Gemfile
Gemfile.lock

- Gem passenger is never used because we use a standalone integration with Nginx
- Gem new relic is never used

Remove useless gems

---

.github/workflows/deploy_production.yml
.github/workflows/release.yml
.github/workflows/tests.yml

On the master branch after all tests pass, 
* generates a default patch release. (see https://github.com/mathieudutour/github-tag-action)
* generates a release on github
* upload an image with the corresponding tag on scaleway registry.

Add release workflow

---

spec/lib/tasks/create_admin_task_spec.rb
spec/lib/tasks/create_system_admin_task_spec.rb

Fix flaky on System admin and admin creation task, ignoring a double call on rspec when testing rake task (TODO added #311 #310)

Fix flaky on Admin and System admin creation

---

app/views/decidim/forms/questionnaires/show.html.erb
spec/commands/decidim/forms/answer_questionnaire_spec.rb
spec/system/survey_spec.rb

This fixes the displaying of images into the surveys
- [Notion card](https://www.notion.so/opensourcepolitics/Angers-bug-affichage-image-fonctionnalit-enqu-te-b6861a22e68d46aa92f74ceba69c4409?pvs=4)

[Fix] - Display of images in surveys

---

app/permissions/decidim/admin/permissions.rb
spec/permissions/decidim/admin/permissions_spec.rb

This PR is here to fix the disappearance of templates from the back office main navbar
- [Notion card](https://www.notion.so/opensourcepolitics/BUG-Disparition-du-module-Mod-le-de-questionnaire-c886ec0ca84a4ee38f4b7a5754af3c5b?pvs=4)
Example:
* Check if "templates" is available
* Check features

[Fix] - Disappearance of templates

---

Dockerfile
Gemfile
Gemfile.lock
README.md
db/migrate/20230612152043_create_decidim_gallery_gallery_items.decidim_gallery.rb
db/migrate/20230612152044_add_gallery_id_to_decidim_static_pages.decidim_gallery.rb
db/schema.rb

Add module gallery
- [Notion card](https://www.notion.so/opensourcepolitics/Sytral-Gallery-cb8c0fd23f8c4506bc7f1e0cdd3ca451?pvs=4)

Add module gallery

---

lib/tasks/decidim_app.rake
spec/lib/tasks/upgrade_task_spec.rb

In the case of the IndieHoster migration, we needed to have a centralized interface in order to perform application updates. In the case of an upgrade, this task allows you to define a Hook that can be enriched with all the methods required during migration, such as resetting the search or synchronizing locals as required.

Add upgrade task

---

lib/k8s_configuration_exporter.rb
lib/k8s_organization_exporter.rb
lib/tasks/k8s.rake
spec/lib/k8s_configuration_exporter_spec.rb
spec/lib/k8s_organization_exporter_spec.rb

Dans les grandes lignes:
Je n'avais pas besoin du sync, je vais le faire en ansible.
Il me fallait un secret spécifique pour la SECRET_KEY_BASE, l'opérateur attends cela.
Et J'ai changé les quelques nom d'objets ci et là, pour correspondre aux attentes de l'opérateur.
```
ssh mako@decidim-migration-dry-run -p 124
cd decidim-app
bundle exec rails k8s:export_configuration IMAGE="rg.fr-par.scw.cloud/decidim-app/decidim-app:develop"
```
Le hostname de cette instance de test est:
```
decidim-migration-dry-run.osp.dev
```
(Et donc les ressources sont nommées sur le sous domaine.)
L'output est:
Le contenu du bucket est bien dans:
```
tmp/k8s-migration/decidim-migration-dry-run/buckets/decidim-migration-dry-run--de/
```
Et le dump pg dans:
``` …
```

feat: improve k8s rake

---

lib/decidim_app/k8s/organization_exporter.rb
lib/decidim_app/k8s/secondary_hosts_checker.rb
spec/lib/decidim_app/k8s/organization_exporter_spec.rb
spec/lib/decidim_app/k8s/secondary_hosts_checker_spec.rb

When a Decidim configuration was exported to Kubernetes, the consequence was that sometimes the secondary host did not point to the primary host, invalidating the deployment since authentication with SSL certificates is performed. 
This could lead to configuration invalidation. 
The aim of this PR is to test the secondary hosts before exporting them, and to retain only the valid ones.
The method chosen for this is to contact the secondary host and follow the redirection until the host is reached, or until the specified number of redirects has expired. 
In this way, we can see whether the secondary host is really pointing to the primary host.

Check if secondary hosts are valid

---

config/initializers/rack_attack.rb

Removed custom definition of Rack attack cache to use default one (Rails.cache)
Defined in:
`rack-attack-6.6.1/lib/rack/attack/cache.rb:9`
with: 
```ruby
def initialize
self.store = ::Rails.cache if defined?(::Rails.cache)
@prefix = 'rack::attack'
end
```

Use Rails cache instead of defining new one

---

docker-compose.yml

Allows to serve assets locally when using docker-compose and ngrok

fix: Assets in docker-compose

---

.github/workflows/ci_cd.yml
app/services/decidim/repair_comments_service.rb
lib/tasks/repair_data.rake
spec/services/decidim/repair_comments_service_spec.rb

This PR adds a rake task to repair comments that are formatted like { "en" => { "en" => "foobar"}}
It turns these into { "en" => "foobar" } and does nothing to the others
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=52077469164a42c68f3e170e24f54f14&pm=c)
Example:
* Change the format of a comment in the database
* run the rake task
* see it goes back to the good format

add service and tasks to repair comments

---

lib/tasks/repair_data.rake
spec/lib/tasks/repair_data_url_in_content_spec.rb

Allow repair task to run and do nothing if en var is not set

Don't raise if env var is not set

---

lib/decidim/content_fixer.rb
spec/lib/decidim/content_fixer_spec.rb

When using repair url sometime a blob is not found, this P.R. rescue this condition and allows the task to continue without issue

fix: Rescue when blob is not found when using repair url

---

Gemfile.lock

Yeah ! There are still some people who use up to date Mac OS (13.5.2) on Intel powered devices 😛

Add x86_64-darwin-22 to platform list in Genfile.lock

---

config/initializers/decidim_initiatives.rb
config/secrets.yml
config/sidekiq.yml
lib/decidim_app/decidim_initiatives.rb
spec/lib/decidim_app/decidim_initiatives_spec.rb

Env var are not applied for initiatives configuration
- [Notion card](https://www.notion.so/opensourcepolitics/CEA-Changement-variables-env-8dad3404607f46b3bb17301012143f42?pvs=4)
Env variables
```
INITIATIVES_CREATION_ENABLED", "auto"
INITIATIVES_SIMILARITY_THRESHOLD", 0.25
INITIATIVES_SIMILARITY_LIMIT", 5
INITIATIVES_MINIMUM_COMMITTEE_MEMBERS", 2
INITIATIVES_DEFAULT_SIGNATURE_TIME_PERIOD_LENGTH", 120
INITIATIVES_DEFAULT_COMPONENTS", "pages, meetings"
INITIATIVES_FIRST_NOTIFICATION_PERCENTAGE", 33
INITIATIVES_SECOND_NOTIFICATION_PERCENTAGE", 66
INITIATIVES_STATS_CACHE_EXPIRATION_TIME", 5
INITIATIVES_MAX_TIME_IN_VALIDATING_STATE", 60
INITIATIVES_PRINT_ENABLED", "auto"
INITIATIVES_DO_NOT_REQUIRE_AUTHORIZATION", "auto"
```

fix: Add initiatives initializer

---

.env-example
config/initializers/decidim.rb
config/secrets.yml

Fix Admin password config
Add variables : 
- `DECIDIM_ADMIN_PASSWORD_STRONG`  default to `false` (`true` in decidim)
- `DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS`  default to `365` (`90` indecidim)
- `DECIDIM_ADMIN_PASSWORD_REPETITION_TIMES`  default to `15`
- `DECIDIM_ADMIN_PASSWORD_MIN_LENGTH`  default to `5`

Load the admin password configuration like decidim-core

---

config/application.rb
lib/extends/services/decidim/iframe_disabler_extends.rb
spec/system/survey_spec.rb

We backport [CD44 - #146](https://github.com/OpenSourcePolitics/decidim-cd44/pull/146) to fix the disappearance of Iframes
Example:
* Go to participatory processes
* Choose the first one
* Add an iframe to the description of it
* Go to the page linked
* Check if iframe appears

fix: Backport fix of disappearance of iframes

---

Gemfile
Gemfile.lock

Allow admins to customize Devise mail translations
Create multiple devise translation customizations :
For account confirmation mails :
Create TermCustomizer entries
devise.mailer.confirmation_instructions.instruction
devise.mailer.confirmation_instructions.subject 
Refresh cache and create a new account
For reset password confirmation :
Create TermCustomizer entries
devise.mailer.reset_password_instructions.subject
Refresh cache and ask a reset password for user@example.org
For new admin invitation
Create TermCustomizer entries
devise.mailer.invite_admin.subject
Refresh cache and invite a new admin

fix: Devise emails

---

Gemfile.lock

We had an issue with notifications not sending onto the 0.27 apps because a change we made in the module term customizer. So as we fixed it on the branch we needed to update the last commit.
Example:
* Log in as user
* Go follow a process
* Log as an admin
* Comment the process that has been followed
* Log as the previous user
* Check if you received the notification

fix: change the commit to fix notifications not sending on dcd-app

---

.gitignore
app/jobs/check_published_initiatives.rb
app/jobs/check_validating_initiatives.rb
app/jobs/notify_progress_initiatives.rb
app/views/decidim/devise/shared/_omniauth_buttons.html.erb
config/sidekiq.yml

This will scheduled daily these 3 rake tasks : 
- `decidim_initiatives:check_validating`
- `decidim_initiatives:check_published`
- `decidim_initiatives:notify_progress`
see : https://github.com/decidim/decidim/tree/release/0.27-stable/decidim-initiatives#rake-tasks
**+** 2 stowaway : 
- add (again) `.DS_Store` files to `.gitignore`
- fix a missing space with erblint

Add missing jobs for initiatives rake tasks

---

config/application.rb
lib/extends/models/decidim/budgets/project_extend.rb
spec/models/decidim/budgets/project_spec.rb

When filtering, it causes a 500 error 
```
ActionView::Template::Error (PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous
oncat(',', id::text, ',') in ',,')...
^
5: </div>
6: 
7: <div class="budget-list">
8:   <% projects.each do |project| %>
9:     <%= render partial: "project", locals: { project: project } %>
10:     <%= render partial: "project_modal", locals: { project: project } %>
11:   <% end %>
```
- Backport from https://github.com/OpenSourcePolitics/decidim-cd44/pull/149
Fixes #476 
With a running Docker env you can setup this application locally by running `make run` and access it at : https://localhost:3000
Example:
* Go to budgets
* Try to filter …

fix: Budgets Project filters Ambiguous ID

---

Gemfile.lock
spec/system/admin/export_initiative_signatures_spec.rb

Downgrade `wicked_pdf` to be compatible with Webpacker.
Add specs
- Related to #458 
- Related to https://github.com/mileszs/wicked_pdf/issues/1098
- [Notion card](https://www.notion.so/opensourcepolitics/Bordeaux-500-error-on-signatures-export-6da1705f36f54902bc72e831effb9fc1?pvs=4)
If you have a Running Docker env you can easily setup using : `make run`

fix: Downgrade wicked_pdf to 2.6.3

---

Gemfile
Gemfile.lock
db/migrate/20240206101716_create_auth_settings.decidim_half_signup.rb
db/migrate/20240206101717_add_phone_number_to_decidim_user.decidim_half_signup.rb
db/migrate/20240206102829_add_main_image_to_decidim_budgets_budgets.decidim_budgets_booth.rb
db/migrate/20240206102830_create_decidim_budgets_user_data.decidim_budgets_booth.rb
db/schema.rb
spec/lib/tasks/decidim_app/k8s/dump_db_tasks_spec.rb
spec/lib/tasks/decidim_app/k8s/export_configuration_tasks_spec.rb
spec/lib/tasks/repair_data_translations_spec.rb
spec/lib/tasks/scaleway/storage/migrate_from_local_task_spec.rb

Addition of both modules budgets booth and half signup to the Marseille's platform
- [Notion card](https://www.notion.so/opensourcepolitics/Marseille-Cr-ation-branche-d-di-e-et-ajout-modules-vote-BP-c2135296278043a9ba0e765a3254da3b?pvs=4)

feat: Add budgets booth and half signup

---

config/sidekiq.yml

When executed at the same time, scheduled jobs can generates instabilities on infrastructure.
It also reduce max retries count from 25 to 5
This PR aims to randomize the moment of each job
- [Notion card](https://www.notion.so/opensourcepolitics/Sidekiq-Randomize-recurring-jobs-06bc512ec6ce4bd7806e589391763f9d?pvs=4)
- Dev, ensure for a 6 digits cron format it matches the comment 
- Product, ensure for each job if the period is not too large

fix: Add random on scheduled jobs and reduce max retries

---

spec/system/locales_spec.rb

It fixes the flaky that was present in the locales spec test because we noticed that 80% of the time user was not logged in properly on the failing test when he should have been.
- Fixes #497 
- [Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-Flaky-spec-in-locales-system-specs-91581b8e9ee9498889b98aa61d54ac44?pvs=4)

fix: Flaky test on locales spec

---

.env-example
.github/workflows/ci_cd.yml
Gemfile
Gemfile.lock
app/views/decidim/account/show.html.erb
config/i18n-tasks.yml
config/initializers/decidim.rb
config/initializers/friendly_signup.rb
spec/commands/decidim/create_registration_spec.rb
spec/lib/decidim_app/k8s/organization_exporter_spec.rb
spec/system/account_spec.rb
spec/system/extra_user_fields/account_spec.rb

When there is only one locale in organization, disable dropdown in user account form. Otherwise displays a dropdown
Also sysadmin can modify default notifications_sending_frequency using env var `NOTIFICATIONS_SENDING_FREQUENCY` = "daily", "weekly", "none", "real_time" through module extra-user-fields

feat: Backport language selector and allow to modify notification sending frequency

---

config/initializers/extends.rb

As an administrator, when I navigate to the Proposal index in the backoffice, an internal server error is raised.
- [Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-Internal-server-error-on-proposals-backoffice-index-1849406e2204436c88abad17095261d0?pvs=4)
Example:
* Go to proposals index
* List should be available
This error is only reproductible in dev mode (not Docker prod mode)

fix: Require exporters before initialization

---

Gemfile.lock

This PR upgrades `decidim-budget_category_voting` and `decidim-category_enhanced` to the latest versions.

Upgrade decidim-category_voting and decidim-category_enhanced

---

.github/workflows/ci_cd.yml

Codecov upload is failing because of a throttling about a limit reached. We must reconfigure account to increase this limit. 
I remove codecov upload from Github Actions workflows for unlocking CI/CD

ci: Disable codecov upload

---

Gemfile
Gemfile.lock

Bump *friendly_signup: with button disabled when the user enters the registration code.
*This module simply substitutes some pages to ease up the registration process in Decidim.
📌 Related Issues
Link your PR to an issue
Related to #?
Fixes #?
[Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-Toulouse-Bump-FSU-c98a83902e6744b2a3039fa721d61598?pvs=4)
Testing
1. Go to sign up
2. Enter the registration code received by mail (The 'verify' button has become disabled)
3. It should automatically display your homepage

fix:bump friendly signup

---

.env-example
Gemfile
Gemfile.lock
config/application.rb
config/i18n-tasks.yml
config/initializers/decidim.rb
config/secrets.yml
lib/extends/controllers/decidim/newsletters_controller_extends.rb
spec/controllers/newsletters_controller_spec.rb

Fix the unsubscribe link in newletters 
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=b64a299d6e2143c88e3a0ee40a075de3&pm=c)
1. as an admin, got to your account and accept newletters
2. as an admin, create a newletter
3. select the recipients "send to all users"
4. click on deliver newsletter
5. go to received email and click on unsubsrcibe link
6. get a message confirming that you are unsubscribed

fix the unsubscribe link in newsletters

---

config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml

Fix missing translation for local_area in participatory_processes show
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=181f0b33244e4710bef8b9054d684fb7&pm=c)
1. Go to /admin/participatory_processes/
2. Edit a participatory_process
3. Complete the metadata “Espace d’organisation” 
4. Update the participatory process
5. Click on "voir la page publique" and see on the  "Espace d'organisation" instead of "organization area”

fix missing translation for local_area in participatory_processes show

---

Gemfile
Gemfile.lock
config/i18n-tasks.yml
config/locales/fr.yml
spec/commands/decidim/budgets_importer/admin/import_project_spec.rb
spec/spec_helper.rb

Add module budgets importer
- [Notion card](https://www.notion.so/opensourcepolitics/Marseille-Rebase-branch-ajout-module-budget-importer-0feda0d027124390a355bb2f42d7c691?pvs=4)
Example:
* Go to Participatory process : http://localhost:3000/admin/participatory_processes
* Click on a PP of the list : http://localhost:3000/admin/participatory_processes/[SLUG]/edit?locale=fr
* Click on Budgets on the "Components" sidebar
* Access the projects page by clicking on the action icon
* Download a sample export by clicking on the dropdown `Export > Export as JSON` (retrieve zip file in the letter opener http://localhost:3000/letter_opener)
* Then …

feat: Add module budgets_importer to Marseille

---

.env-example
Gemfile
Gemfile.lock
app/services/decidim/sms_gateway_service.rb
config/initializers/decidim.rb
config/secrets.yml

Just a few clean up for the SMS Gateway Service configuration vars : 
- load env vars as secrets
- add errors message (non blocking) in `Decidim::SmsGatewayService` when required vars are missing
- bump [decidim-module-half_sign_up](https://github.com/OpenSourcePolitics/decidim-module-half_sign_up) to initialize the service with the code instead of the message

Fix: SMS Gateway Service

---

Gemfile
Gemfile.lock

Change the half sign up module branch from `feature/half_signup_and_budgets_booth` to `main` for Marseille instance. 
Example:
* See ...

Fix: Change half_sign_up module branch

---

Gemfile
Gemfile.lock
app/views/decidim/budgets/line_items/update_budget.js.erb

As a user, when I click on _read more_ on projects list, a modal open with a button "Add to your vote", on click an infinite loader is spinning 
It is related to an incompatibility between budgets-category & budget-booth.
- Fixes #?
- [Notion card](https://www.notion.so/opensourcepolitics/Angers-Infinite-loader-on-Details-vote-button-e9e655a9c6e8486d8247fa8df227c9f8?pvs=4)
Example:
* Run application with deface enabled `DEFACE_ENABLED=true bundle exec rails s`
* Access Participatory Process
* Create a budget
* Define categories
* Go to the budget booth
Merge of 2 overrides from different modules into a single file : …

fix: JS incompatibility between budgets-category & budget-booth

---

Gemfile
Gemfile.lock

Bump Decidim Awesome to the last commit in order to benefit from the following fix: https://github.com/decidim-ice/decidim-module-decidim_awesome/pull/301
Related to  Image upload not working in the front office for fields created with custom proposal fields  decidim-ice/decidim-module-decidim_awesome#297
* Access Awesome module in back office
* Enable rich text editor for participants and create custom proposal field with text area (the rich text editor option must also be enabled for the custom fields) 
* In front office, create a new proposal and add an image in the custom proposal field
* Publish your proposal and see that the image is displayed correctly 
👉 Because this is a hotfix that needs to be deployed ASAP for a client, we are not going through the usual …

Hotfix: Bump Decidim Awesome module

---

config/application.rb
lib/extends/controllers/decidim/proposals/proposals_controller_extends.rb
spec/controllers/decidim/proposals/proposals_controller_spec.rb

In an assembly on proposals index view, sometimes  in the filters, a scope is not checked because its children are not checked while they should be all checked when loading the page.
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=1988f63b9b3e4cb6abd1e2b4bcbc53cc&pm=c)
1. As an admin, create an assembly with scopes enabled, choose a scope that has subscopes (like "Indiana"), or choose one assembly that has scopes enabled and a scope.
2. As an admin, go to parameters > scopes > Indiana, click on one of its subscopes (like [Grimesstad) and  add subscopes to it
3. As a user, go to the assemblies > assembly > proposals and see in the …

Fix parent scope filter

---

lib/extends/lib/decidim/forms/user_answers_serializer_extend.rb

When exporting a meeting without data in the registration form, answer can be `nil` in the `user_data` method. 
This was causing crash on the meeting participants export.

fix(exports): add safe navigation operator on answer param

---

spec/lib/tasks/decidim_app/sms_reminder_task_spec.rb

Add tests for sms_reminder rake task
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=35d7b284cc354e0bb81a5a612170d499&pm=c)
bundle exec rspec spec/lib/tasks/decidim_app/sms_reminder_task_spec.rb
- [X ] Add specs

test: add tests for sms_reminder rake task

---

app/cells/decidim/initiatives_votes/vote/show.erb
app/cells/decidim/initiatives_votes/vote_cell.rb
app/controllers/decidim/initiatives/admin/initiatives_controller.rb
app/views/decidim/initiatives/admin/initiatives/_signatures.html.erb
app/views/decidim/initiatives/admin/initiatives/export_pdf_signatures.html.erb
app/views/decidim/initiatives/admin/initiatives/export_pdf_signatures.pdf.erb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
spec/cells/decidim/initiatives_votes/vote_cell_spec.rb
spec/system/admin/export_initiative_signatures_spec.rb

Currently all the initiatives signatures PDF file have always the columns "Name and surname", "Document number" and "Date of birth". This doesn't make much sense as this should depend if the Intiative Type has the " Collect participant personal data on signature " setting enabled.
This PR takes into account this setting to show these columns in the export PDF file.
- Fixes #?
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=016bfb32d01f4373be6c0c53bb6ce6e5&pm=c)
1. As an admin, go to http://localhost:3000/admin/initiatives
2. Then, click in "Edit' (pencil) of an initiative, check which Initiative type this Initiative has. Go to that Initiative type and check that " …

Backport initiatives exports pdf

---

Dockerfile.local
Makefile
docker-compose.local.yml

Rewrite local Docker configuration 
**Local app**
- Start Docker Desktop app
- Run app locally : `make run`
- Access using https://localhost:3000
**On local network**
- Run `make external`
- Access : https://[IP]:3000
⚠️ This configuration does not change production configuration

feat: Optimize local docker build

---

app/views/decidim/half_signup/quick_auth/sms.html.erb
config/i18n-tasks.yml
config/locales/fr.yml

This PR changes the text on the sms authentication method for Marseille and also adds a link to the terms and conditions to replace the appearance of it after the creation of the account.
- [Notion card](https://www.notion.so/opensourcepolitics/Marseille-CGU-1ed988bbd0d14a7886620bec320eeccc?pvs=4)
Example:
* Go to authentication settings
* Enable SMS method and save your organization
* Log out 
* Change your locale to french
* Try to login
* Make sure that you have the translation and that you can access the Terms&Conditions by clicking on the link

feat: Change SMS text to include terms & conditions

---

app/services/decidim/download_your_data_exporter.rb
lib/decidim/seven_zip_wrapper.rb
spec/services/decidim/download_your_data_exporter_spec.rb

When I load my personal data, I receive an email with a zip file and a password to open it. The password is now functional, I can open the file and access my personal data.
- Related to https://github.com/decidim/decidim/issues/13037
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=54547f3ef83a4d1e806cdeee4a43cf60&pm=c)
- Backport de  https://github.com/decidim/decidim/pull/13185/files
1. After login, go to "My account"
2. Go to "My data"
3. Click on "Request data"
4. Go to you mail and download the zip file
5. Open the zip file and enter the password provided in the mail
6. See that you open the zip and access to your personal data file

backport: seven zip ruby as cli wrapper

---

app/jobs/decidim/export_job.rb
config/initializers/extends.rb
lib/extends/lib/decidim/phone_authorization_handler/proposal_serializer_extend.rb
spec/jobs/export_job_spec.rb

This PR fixes the issue of not receiving infos from the author of a proposal when exporting as a user who's an administrator from a processes and not an administrator from the platform.
- [Toulouse & decidim-app - Non extraction des mails dans les exports de propositions pour les admins d’espace](https://www.notion.so/opensourcepolitics/Toulouse-decidim-app-Non-extraction-des-mails-dans-les-exports-de-propositions-pour-les-admins-d-2f782358512a4ff1a2e043d661677f99?pvs=4)
- [fix: Export issue for Processes Administrators #231](https://github.com/OpenSourcePolitics/decidim-tou/pull/231)
Example:
* Sign in as an admin 
* Go to a proposal component with published proposals
* …

backport: Export issue for Processes Administrators

---

.github/workflows/ci_cd.yml
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
spec/jobs/export_job_spec.rb

Addition of missing translations keys for the dropdown export button in admin proposals index.
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=fff5d39996a78063a0a8c6a37ff033d8&pm=c)
1. As an admin, go to a process
2. Got to proposals
3. Click on "Export" button and see that you have the needed translations fo the different types of exports.
4. Change the language for french and see that you have the needed translations

Fix: add missing translations for export dropdown in proposals admin

---

Gemfile
Gemfile.lock
app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb
config/locales/en.yml
config/locales/fr.yml
db/migrate/20240904084430_add_deleted_at_to_proposals.decidim_simple_proposal.rb
db/schema.rb
spec/controllers/decidim/proposals/proposals_controller_spec.rb
spec/system/proposals_spec.rb

This PR has been made to add the module simple_proposal to the DCD-App on the release 2.4
- [Release Decidim-app 2.4 - Ajout module simple proposal](https://www.notion.so/opensourcepolitics/Release-Decidim-app-2-4-Ajout-module-simple-proposal-9b90cee7ccc142f195efae457a468d14?pvs=4)
* Log in as an admin
* Access to backoffice to a process
* Access to the proposal component and update it selecting a scope and make sure category selection and scope selection are mandatory for creating proposals
* Apply changes
* Access to front office to the proposal component
* Create a new proposal
* Make sure you see two new mandatory selectors and make sure that you can still create proposal

feat: Add simple proposal gem

---

OVERLOADS.md
app/cells/decidim/version_cell.rb
spec/cells/decidim/version_cell_spec.rb

On the meeting versioning show page, a reflected XSS injection vulnerability is present. 
https://github.com/user-attachments/assets/5c0d3276-434e-4538-8dfb-9f31d57fd346
- [Notion card](https://www.notion.so/opensourcepolitics/CEA-Reflected-XSS-on-meetings-versions-e48ed34acf27407e97d35967b5c083f7?pvs=4)
1. Create a new meeting (make sure the option "users can create meetings" is enabled in the dashboard if needed) and edit it once.
2. Go to the public page of the meeting.
3. Select the second version of the meeting (e.g., https://localhost:3000/assemblies/exhibition-general/f/24/meetings/65/versions/2).
4. In the URL, add at the end: 'XSS%3Cmarquee%20onstart=alert(1)%3Ex or '%3Cmarquee%20onstart=alert(1)%3Ex.
5. You should not see any JavaScript animation (like in the video above) next …

Fix reflected XSS on meetings versions

---

app/views/decidim/budgets/projects/_count.html.erb
config/i18n-tasks.yml

- [Marseille - Affichage projets](https://www.notion.so/opensourcepolitics/Marseille-Affichage-projets-1ed968ac3dab4027a73735aec0378073?pvs=4)
Example:
* Access your platform
* Change locale to french
* Access a process
* Go to a budget (find another one if it is locked using zipcode method
* Try to filter projects (with some results or not)
* Make sure that it shows the right translation everytime

fix: Wrong translation key displayed on projects counts

---

config/locales/fr.yml

Change the order_reminder translation in the fr.yml

fix: Change order_reminder translation to match Marseille's request

---

Gemfile
Gemfile.lock
app/views/decidim/proposals/proposals/index.html.erb
app/views/decidim/proposals/proposals/index.js.erb
config/locales/en.yml
config/locales/fr.yml

* fix: Disable deface override from proposals' index to reenable filters
* fix: Move the file to the right place
* fix: Add missing js file and fix tests
* fix: Add missing feature about caching geocoded proposals
* fix: Update to fix the encoding of the link for geocoded proposals

hotfix: Fix proposal index filters that were not working (#595)

---

Gemfile
Gemfile.lock
app/jobs/drupal_decisions_job.rb
app/models/drupal/abstract_record.rb
app/services/decidim/drupal_decisions_importer_service.rb
app/services/decidim/drupal_importer_service.rb
app/services/decidim/drupal_page.rb
config/database.yml
lib/tasks/import.rake

Add bilans and decisions for each url.
Example:
* Add file `tmp/links.csv` with a single column header `url`
* Create all processes : (You can seed with this command) `BASIC_AUTH_USER=... BASIC_AUTH_PASSWORD=... bundle exec rake import:pps`
* Edit all existing decisions pages : `BASIC_AUTH_USER=... BASIC_AUTH_PASSWORD=... bundle exec rake import:bdx:decisions` 
* Go to processes
* See decisions components

feat(bordeaux): Create rake task to import bilans and decisions

---

.env-example
OVERLOADS.md
app/controllers/decidim/assemblies/assemblies_controller.rb
app/controllers/decidim/participatory_processes/participatory_processes_controller.rb
app/helpers/decidim/assemblies/assemblies_helper.rb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
config/secrets.yml
db/seeds.rb
spec/controllers/assemblies_controller_spec.rb
spec/controllers/participatory_processes_controller_spec.rb

Allow custom sort of participatory processes depending on environment variable (this is a backport of a specific feature from decidim-tou)
- [Odoo card](https://opensourcepolitics.odoo.com/web#id=2578&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
1. As an admin, go to an assembly, add Related participatory processes and update.
2. As a user, go to the show page of the assembly and see that Related participatory processes are not sorted (cf screenshot 1)
3. Stop your server and relaunch it with `SORT_PROCESSES_BY_DATE=true bundle exec rails s`
4. As a user, go to the show page of the assembly and see that Related participatory processes are sorted with (cf screenshot 2):
- active first …

Feat: custom sort for processes

---

app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb
config/i18n-tasks.yml
spec/controllers/decidim/proposals/proposals_controller_spec.rb

When a user tried to add a new proposal, the appropriate error message* was not displayed when the proposals limit was reached.
- Fixes #?
- [Odoo card](https://opensourcepolitics.odoo.com/mail/view?model=project.task&res_id=3095&access_token=1837be14-8706-47c9-987c-f6fea516c7b7)
- As admin go to a participatory process
- Go to the settings proposals component 
- Add a poposal limit 
-
- On the frontend, create a new proposal in the correct process
- You should see an error alert "You can't create new proposals since you've exceeded the limit." *
-

fix error message displaying when reaching proposition add limit

---

Gemfile
Gemfile.lock
config/sidekiq.yml

Bump module spam detection bot and add new rake task usable from the Sidekiq interface

fix: Add block reported user task

---

app/packs/src/decidim/decidim_awesome/admin/custom_fields_builder.js
app/packs/src/decidim/decidim_awesome/forms/custom_fields_renderer.js
config/initializers/awesome_defaults.rb

Backport of this PR https://github.com/OpenSourcePolitics/decidim-tou/pull/234
- [Odoo card](https://opensourcepolitics.odoo.com/web#id=3393&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
1. Open the network (right click + inspect + check on the right until you find "Network")
2. Switch to French Language
3. Filter using the search bar for "fr-FR"
5. Keep the network open and as an admin, go in the BO to decidim_awesome tab, and then click  on proposals custom fields and then on public or private fields and add a field
6. Make sure you see the fr-FR.lang and than when you click on it you see this url https://decidim.storage.opensourcepolitics.eu/osp-cdn/form_builder/1.1.0 linked to the file

Backport self hosted cdn

---

Gemfile
Gemfile.lock

- Allow to reduce the spam probability score using env var `SPAM_DETECTION_BLOCKING_LEVEL`
Used in `bundle exec rake decidim:spam_detection:block_users`
* `SPAM_DETECTION_BLOCKING_LEVEL` (default: 0.99) OPTIONAL

bump: Module Spam Detection

---

app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb
config/i18n-tasks.yml
spec/controllers/decidim/proposals/proposals_controller_spec.rb

Reverts OpenSourcePolitics/decidim-app#609 
Due to the following error: 
```
2024-11-20 15:43:08.377	[781a53a85e201ca2e4d0f0ca02a9febb] app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb:59:in `create'
2024-11-20 15:43:08.377	[781a53a85e201ca2e4d0f0ca02a9febb] app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb:200:in `proposal_limit_reached?'
2024-11-20 15:43:08.377	[781a53a85e201ca2e4d0f0ca02a9febb] app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb:204:in `current_user_proposals'
2024-11-20 15:43:08.377	[781a53a85e201ca2e4d0f0ca02a9febb]   
2024-11-20 15:43:08.377	[781a53a85e201ca2e4d0f0ca02a9febb] NoMethodError (undefined method `id' for nil:NilClass):
2024-11-20 15:43:08.377	F, …
```

Revert: "fix error message displaying when reaching proposition add limit"

---

app/commands/admin/reorder_scopes.rb
app/forms/decidim/user_interest_scope_form.rb
app/forms/decidim/user_interests_form.rb
app/helpers/concerns/decidim/simple_proposal/scopes_helper_override.rb
app/packs/entrypoints/application.js
app/packs/entrypoints/decidim_custom_scopes.scss
app/packs/src/decidim/admin/reorder_scopes.js
app/packs/stylesheets/decidim/scopes/_scopes-custom.scss
app/views/decidim/admin/scopes/index.html.erb
config/application.rb
config/locales/en.yml
config/locales/fr.yml
db/migrate/20240412112810_add_weight_to_scopes.rb
db/schema.rb
lib/extends/controllers/decidim/admin/scopes_controller_extends.rb
lib/extends/controllers/decidim/scopes_controller_extends.rb
lib/extends/helpers/decidim/check_boxes_tree_helper_extends.rb
spec/helpers/decidim/check_boxes_tree_helper_spec.rb
spec/system/admin_manages_organization_scopes_spec.rb

This PR is a backport from a feature made for Toulouse.
It allows administrators to sort the scopes however they want using a drag and drop system and displays it in multiple features in front-office like : 
- User interests (/user_interests)
- Scopes filters onto everywhere that calls the checkbox_trees_helper.
- Scopes selection modal
* Go to settings
* Access to scopes
* Check that you can sort (sort and refresh to make sure everything stays in place)
* Access onto a scope and try to sort the subscopes (same tests as above)
* Go to a process and activate the scopes on a proposals component
* Check the pages that we quoted above and check that everything is well sorted
* You can repeat the process multiple times to check that it's always sorted …

backport: Addition of sortable scopes using drag and drop 

---

app/views/decidim/proposals/proposals/index.html.erb

This PR removes the cache from the proposals index related to geocoded proposals because it caused when the app has a cache mechanism, to create an issue where the map wasn't reloading anymor when index of the proposals is cached.
- [Release 2.5.1 - Geocoding map is not displayed](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=guillaume%40opensourcepolitics.eu&token=ixqNZ9S5lGRCj9ADpsQq#id=3425&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
----------------
* Go to participatory processes
* Access PP and a "Components"
* Access to the options of a Proposals component
* Enable Geocoding 
---
* Access this proposals index on front-office
* Make sure the map is appearing the first time 
* Refresh a few times …

fix: Map not displaying when refreshing

---

config/environments/production.rb

If smtp user_name or smtp password is not defined, then smtp_settings "Authentication" key must not be defined
Related to [card](https://opensourcepolitics.odoo.com/web#id=3557&cids=1&model=project.task&view_type=form)

fix: Add authentication only if user_name & password

---

config/application.rb
config/locales/en.yml
config/locales/fr.yml
lib/extends/controllers/decidim/comments/comments_controller.rb
lib/extends/forms/decidim/comments/comment_form_extends.rb
spec/controllers/decidim/comments/comments_controller_spec.rb
spec/forms/comment_form_spec.rb

This PR fixes the fact that the char limit didn't apply when trying to edit a comment and it was always the default value "1000" chars that was selected.
- [Problème avec la modification des commentaires (présent sur la Decidim APP)](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=guillaume%40opensourcepolitics.eu&token=ixqNZ9S5lGRCj9ADpsQq#id=3488&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
Example:
* Go to participatory processes and access one to go to the proposals component of it
* Modify the component to fix a limit of characters (Default is 0 but increase it to over a thousand)
* Access Front-Office of this component
* Access a proposal and submit a comment over 1000 …

fix: Fix characters limits when editing comments

---

app/controllers/decidim/system/dashboard_controller.rb
app/jobs/concerns/decidim/logging.rb
app/jobs/decidim/papertrail_versions_job.rb
app/views/decidim/system/dashboard/show.html.erb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
config/secrets.yml
config/sidekiq.yml
lib/tasks/db.rake
spec/jobs/decidim/papertrail_versions_job_spec.rb

PaperTrail Versions are never cleaned in database. These versions are created whenever a resource is created or updated and Decidim.traceability configured.
These versions are accessible in front for proposals and initiatives.
This PR add a new rake task to be able to clear versions table and also a new Job configured to run every day at 3 AM with Sidekiq.
Command : `bundle exec rake decidim:db:versions:clean`
By default, retention period is set to 6 months. Newer version won't be removed.
It is editable through env var `DECIDIM_DB_VERSIONS_RETENTION=6`
- Related to IndieHosters Database Weight
Example:
* Run rails console
* Get existing versions : …

Clear versions in database

---

app/controllers/concerns/decidim/budgets/orderable.rb
config/i18n-tasks.yml
config/initializers/default_sort_order.rb
config/locales/en.yml
config/locales/fr.yml
spec/lib/decidim/budgets/admin/component_spec.rb
spec/system/sorting_projects_spec.rb

This adds a new sort for the projects of budgets that is now updatable in the BackOffice and which is the alphabetical one
- [Feature - Nouvelle option de tri des projets par ordre alphanumérique](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=guillaume%40opensourcepolitics.eu&token=ixqNZ9S5lGRCj9ADpsQq#id=3625&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
*Steps to validate your PR:*  
1. Log in as an admin.  
2. Go to the Backoffice.  
3. Navigate to a participatory process.  
4. Open the settings for a budgets component.  
5. Enable the default sort (e.g., alphabetical or another option you want to test).  
6. Access a budget within the updated component.  
7. Check that:  
- The default sort is applied correctly when you arrive.  
- The …

feat: Alphabetical order addition for Budgets' Projects

---

app/jobs/clear_duplicated_half_signup_users_job.rb
app/jobs/concerns/decidim/logging.rb
app/jobs/decidim/papertrail_versions_job.rb
lib/tasks/clear_duplicated_users.rake
lib/tasks/db.rake
spec/jobs/clear_duplicated_half_signup_users_job_spec.rb

This PR adds a rake task that will delete duplicated half signup users, and alert the administrator about the decidim accounts that contains a phone number that might be duplicated in the DB (multiple decidim accounts with the same phone number)
- Generate your App
- Access to the db generated with your application
- Access the table decidim-users
- Target a dozen of users that you can easily update (that were not already deleted or blocked on the organization)
- For a multiple case scenarios I would recommend to change 6 users to match the "quick_auth" regex email and to let 6 decidim users with "classic" emails
- For 3 of each, add an identical phone_number with an identical phone_country
- For 1 of each, add an identical phone_number …

feat: Creation of a rake task to delete duplicated half signup users

---

app/jobs/archive_users_phone_job.rb
lib/tasks/clear_duplicated_users.rake
lib/tasks/db.rake

Add rake task `bundle exec rake decidim:db:users:phone` to archive all phone numbers from decidim users and half signup accounts

fix: Add Archive Phone Users

---

.github/workflows/ci_cd.yml
app/overrides/decidim/budgets/projects/show/fix_videos_and_images_display.html.erb.deface

This PR fixes the fact that medias were not displayed when they were on a description of a project on the main page of it (show.html.erb). This was occured by the changing of sanitizing editor allowing only the admin editor to display medias.
We had a deface override to fix it and allow again the display of videos on a project's description
- [Odoo Card]()
* Go to a participatory process on its budgets component
* Access a particular project and edit the description adding a media like an image or a video into it 
* Access front office
* Access the project previously edited
* Make sure the media is displayed correctly

fix: Fix displaying of medias on a project's page

---

app/packs/src/decidim/direct_uploads/upload_modal.js

This PR fixes the issue where media files with names containing apostrophes could not be removed.
To address this, we updated two lines in the JS file (since we cannot extend it). The specific lines modified are [Line 182](https://github.com/OpenSourcePolitics/decidim-app/blob/4e27d93a389a4985b6c35ad9168f60885651c81e/app/packs/src/decidim/direct_uploads/upload_modal.js#L182) and [Line 256](https://github.com/OpenSourcePolitics/decidim-app/blob/4e27d93a389a4985b6c35ad9168f60885651c81e/app/packs/src/decidim/direct_uploads/upload_modal.js#L256) from
`app/packs/src/decidim/direct_uploads/upload_modal.js`, replacing single quotes with double quotes to prevent crashes when apostrophes are present.
* Try to update homepage image …

fix: Blocked interactions with medias misnamed

---

Gemfile
Gemfile.lock
config/i18n-tasks.yml
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
db/migrate/20250220125330_create_decidim_admin_multi_factor_settings.rb
db/schema.rb
spec/services/deepl_translator_spec.rb
spec/system/admin_double_authentication_spec.rb

The aim of this PR is to add decidim-admin_multi_factor to the decidim-app.
- [Odoo card](https://opensourcepolitics.odoo.com/odoo/all-tasks/3936)
Log in as admin and access back office
In the settings, go to Multifactors settings, check the 3 checkboxes and update (see screenshot)
Log out
Log in again and try to access admin dashboard from the menu
Choose email and go to letter_opener to get the verification code
See that you get access to BO
Log out
Log in again and try to access admin dashboard from the menu
Choose sms and search in your logs for "verification code is", and type the code
See that you get access to BO
[X] add specs for admin double authentication

feat: add module 2FA

---

.env-example
.gitignore
Gemfile
Gemfile.lock
app/overrides/decidim/forms/admin/questionnaires/_question/add_drag_and_drop_class.html.erb.deface
app/overrides/decidim/forms/admin/questionnaires/_separator/add_drag_and_drop_class.html.erb.deface
app/overrides/decidim/forms/admin/questionnaires/_title_and_description/add_drag_and_drop_class.html.erb.deface

Addition of Deface and override files to add the missing class managing the Drag & Drop System removed from 0.28 to 0.29
- [BUG 0.29 - Drag and drop non fonctionnel sur les Enquêtes](https://opensourcepolitics.odoo.com/odoo/all-tasks/4277)
Example:
* Go to a participatory process
* Navigate through a survey component or create a new one
* Create some questions (don't forget to name them to see properly the order)
* Create some separators and some titles/descriptions
* Shuffle them using the drag & drop
* Test that the buttons are still working

fix: Drag & Drop Missing in Questionnaires 0.29

---

app/views/layouts/decidim/admin/assemblies.html.erb

The aim of this PR is to fix a bug that occurs on [decidim-0.29.osp.dev](http://decidim-0.29.osp.dev/), but not in local env or docker. When trying to edit a "Hero image and CTA" block in assembly landing page, the error to fix is :  
```
ActionView::Template::Error (undefined local variable or method `parent_assembly' for #<ActionView::Base:0x000000095185c0>):
1: <% content_for :breadcrumb_context_menu do %>
2:   <div class="process-title-content-breadcrumb-container-right">
3:     <% if allowed_to? :create, :assembly, assembly: parent_assembly %>
4:       <% link = defined?(parent_assembly) ? new_assembly_path(parent_id: parent_assembly&.id) : new_assembly_path %>
5:       <%= link_to link, class: "button button__sm button__transparent …
```

fix: add check for parent_assembly in view

---

Gemfile.lock

This release contains a hotfix to replace HERE with Openstreetmap on the homepage interactive map module. 
Thank you! 💟

Feat(release): v2.8.1

---

lib/tasks/repair_data.rake

Proposals and comments returns Internal Server Error in production after migrating to Decidim-app
[Proposal data move migration](https://github.com/decidim/decidim/blob/83be368eb17d4a1b77512dbb59ed2bff04e40246/decidim-proposals/db/migrate/20200708091228_move_proposals_fields_to_i18n.rb#L45) has been run twice
And so [Comment data move migration](https://github.com/decidim/decidim/blob/a04d63a325ed94c49c8a20e4912ce4a9200f243b/decidim-comments/db/migrate/20200706123136_make_comments_handle_i18n.rb#L17) 
Stacktrace : 
```
ActionView::Template::Error (undefined method `to_str' for {"nl"=>"------"}:Hash
```
Command to run
```
bundle exec rake decidim:repair:proposals_locales
bundle exec rake decidim:repair:comments_locales
bundle exec rake …
```

fix(rake): Repair Proposals and Comments i18n data (#695)

---

app/views/layouts/decidim/_mailer_logo.html.erb

The aim of this PR is to fix the error ActionView::Template::Error:unexpected value at params[:host]
that occured in sidekiq when trying to sign up or to reset a password (cf screenshot one). 
The error was linked to the line `organization.attached_uploader(:logo).variant_url(:medium, host: organization.host)` in mailer_logo partial, and has been fix by removing the host.
- [Odoo card](https://opensourcepolitics.odoo.com/odoo/all-tasks/4340)
You need to be in Docker to test this PR 
1. As an admin, go to the settings in the BO
2. Go to Appearance page and add a logo image
3. Log out
4. In a new tab, connect to https://localhost:3000/sidekiq
5. In the app, go to log in, and then to Forgot your password?
6. Fill your email and click on "send me reset password instructions"
7. Go to sidekiq …

fix: remove host from variant_url in mailer_logo partial

---

app/views/decidim/initiatives/create_initiative/fill_data.html.erb

The purpose of this PR is to get rid of the error 'There is an error in this field' on title input in /create_initiative/fill_data, due to autofocus on the input.
To do this, we have to override the fill_data view.
- Fixes https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=103663176&issue=OpenSourcePolitics%7Cdecidim-app%7C712?
1. In the FO, go to /initiatives
2. Click on the "New initiative" button
3. (If two types of initiative are configured) choose an initiative type
4. At the initiative creation step,  see that there is no error on the title field.

fix error on title field in initiative new view

---

config/application.rb
lib/extends/forms/decidim/system/base_organization_form_extends.rb

Remove the length validation (128 characters) added on the organization form in `/system` backend. 
If the `SECRET_KEY_BASE` is shorter than 128 characters, the organization form (create / edit) doesn't validate with the error message : 
```
EN : You need to define the SECRET_KEY_BASE environment variable to be able to save this field
FR : Vous devez définir la variable d'environnement SECRET_KEY_BASE pour pouvoir enregistrer ce champ
``` 
While we create a rake tasks to update short `SECRET_KEY_BASE` we need to temporary remove this validation to be able to update existing platform.

Fix(system): remove Secret key length validation on organization form

---

app/views/decidim/proposals/admin/imports/_proposals_fields.html.erb
config/initializers/extends.rb
lib/extends/lib/decidim/proposals/import/proposal_creator_extends.rb
spec/lib/decidim/proposals/import/proposal_creator_spec.rb

The aim of this PR is to set the co-author of the proposals imported by file to the Organization, so that the author appears as "Official proposal".
- Fixes https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=103716385&issue=OpenSourcePolitics%7Cdecidim-app%7C713?
1. As an admin, export proposals as a CSV or XLS file
2. Import proposals from the file in a new proposal components
3. See that in FO the author of the imported proposals is "Official proposal"
- [X ] Add specs

Feat: modify coauthor in proposals file import

---

config/locales/nl.yml

This PR introduces the nl.yml translation file to address missing Dutch translations within the application.
- Related to [#13 - Add nl.yml file on decidim-app for CultuurConnect](https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=107028606&issue=OpenSourcePolitics%7Cprivate-tasks%7C13)
**Describe the best way to test or validate your PR:**
1. In `config/initializers/decidim.rb`, update [lines 15 and 16](https://github.com/OpenSourcePolitics/decidim-app/blob/develop/config/initializers/decidim.rb#L15-L16) to the following:
```ruby
config.default_locale = ENV.fetch("DEFAULT_LOCALE", "nl").to_sym
config.available_locales = ENV.fetch("AVAILABLE_LOCALES", "nl").split(",").map(&:to_sym)
```
2. Set up your database seeds.
3. Log in as an …

feat: Add nl.yml file and translate e-mails

---

Gemfile
Gemfile.lock
lib/extends/controllers/decidim/devise/omniauth_registrations_controller_extends.rb
spec/controllers/omniauth_registrations_controller_spec.rb

This adds tests to the omniauth controller and backports the nil safety for the controller that caused an issue regarding half-signup
- Fixes #739

test: Add tests for the omniauth controller extends

---

.env-example
app/views/decidim/proposals/proposals/_edit_form_fields.html.erb
config/application.rb
config/i18n-tasks.yml
config/initializers/decidim.rb
config/locales/en.yml
config/locales/fr.yml
config/secrets.yml
docker-compose.yml
lib/extends/commands/decidim/proposals/create_proposal_extends.rb
spec/commands/decidim/proposals/create_proposal_spec.rb

This PR fixes the display of the map on 0.29 by changing the config to the new version and adapting new env vars
**Please make sure you have a `.env` and you may need to use the docker image updating the docker-compose below [#L90](https://github.com/OpenSourcePolitics/decidim-app/blob/develop/docker-compose.yml#L22) (`command: [ "bundle", "exec", "rails", "server", "-b", "ssl://0.0.0.0:3000?key=/opt/decidim/tls-certificate/key.pem&cert=/opt/decidim/tls-certificate/cert.pem" ]`)**
```
env_file:
- .env
```
In your .env file make sure to at the very least put the following var
`MAPS_API_KEY=<your_api_key> `
And if you use docker use the command `make run` it will be easier then follow those steps 
- Let the seeds run to ensure you have some upcoming meetings  
- Go to the homepage and …

fix: Fix maps display on 0.29

---

Gemfile.lock

This just bumps the spam detection module to its last commit to fix the issue of usernames when the module is trying to block the user

bump: Spam detection

---

.env-example
app/overrides/decidim/account/show/disabled_omniauth_synced_nickname_field.html.erb.deface
config/application.rb
config/initializers/omniauth.rb
config/locales/en.yml
config/locales/fr.yml
config/secrets.yml
lib/extends/controllers/decidim/account_controller_extends.rb
lib/extends/forms/decidim/omniauth_registration_form_extends.rb

1. Nickname is excluded from the forced profile sync on omniauth connection
2. When env variable `OMNIAUTH_IGNORE_NICKNAME` is set to `true`, the nickname from the Omniauth data is ignored on account creation (decidim will use the name to generate a nickname)

feat(sso): Exclude nickname from tne force profile sync on omniauth connection

---

config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml

Changes the half signup instructions on the sms authentication page from 
Le numéro de téléphone sera votre clé d'accès à la plateforme. À moins que vous n'ajoutiez un mot de passe à votre compte, un SMS sera envoyé à votre numéro de téléphone chaque fois que vous souhaitez vous connecter
to 
Après avoir saisi votre numéro de téléphone vous allez recevoir un code par SMS. 
Ce code vous donnera accès à la cabine de vote.
Example:
* Change your locale to the french one
* Go to authentication settings
* Enable Half Signup SMS method
* Go to participatory processes
* Select the budgets component of a PP
* Make sure to disable zipcode if it is enabled and to be able to vote …

fix: Change instructions translation to match the behavior

---

app/cells/decidim/footer_topics/show.erb
config/locales/en.yml
config/locales/fr.yml

On decidim, they added categories to the footer, but the issue is that they created the "Help" cells and they hard-coded the title as "Help" which was not following any translation
* Compile your app on docker (if you already have one you can run `make rebuild`
* Make sure you're on french locale
* Go to the bottom of the page
* Make sure the "Help" has been translated to "Aide"
- Fixes #783

fix: Add missing "Help" translation to the footer

---

Gemfile
Gemfile.lock

This PR adds the module guest_meeting_registration
Github card => https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=111943553&issue=OpenSourcePolitics%7Cdecidim-app%7C798
1. As an admin, go to a meeting, enable registration on the platform in the configuration form
2. In the managing meeting's page, in the configure registration page, enable registration without a user account, and enable "Allow cancellation of registration"
3. As a non logged-in user, in the FO, go to the meeting and click on the registration button. See that you have the choice to register with your account or as a guest (Test the 2 processes). See that you can cancel your registration.
4. As an admin, go back to the configure registration page of the meeting and click on "No longer …

Feat: add module guest_meeting_registration

---

config/initializers/decidim.rb

This PR updates the static default url for here.
As a user, go to the show of a geocoded proposal and see that the map is well displayed
- Fixes https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=115435902&issue=OpenSourcePolitics%7Cdecidim-app%7C813

Fix here url for static url

---

config/application.rb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
lib/extends/helpers/decidim/omniauth_helper_extends.rb
spec/factories.rb
spec/helpers/decidim/omniauth_helper_spec.rb

This PR allows to to change the translation of the log in button via the term customizer when Publik is enabled on the platform.
1. Go to an application where publik is enabled
2. As an admin, in the BO, go to Term customizer tab
3. Create a new translation set
4. Inside it, create a new translation with translation key "decidim.devise.shared.links.log_in_with_provider", set a customized term to it and save
5. As a non logged in user, go to the log_in page and see that the log_in btn for publik displays the customized term
- Related to https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=116529871&issue=OpenSourcePolitics%7Cdecidim-app%7C819

Fix publik translation of log_in button to customize it with term customizer

---

Gemfile.lock

This PR bumps decidim-module-extra_user_fields to include style udpate on date_of_birth field
1. As an admin, in the BO, go to settings and then to Manage extra user fields 
2. Enable extra user fields and Enable date of birth field, and two more fields
3. In the FO, go to my account
4. See that the date of birth field is displayed without extra space compare to other fields
5. Log out
6. Go to signup page and see that the date of birth field is displayed without extra space compare to other fields
- Fixes https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=117229980&issue=OpenSourcePolitics%7Cintern-tasks%7C52
**Account form**
**Sign up form**

feat: bump extra_user_fields 

---

app/overrides/replace_default_meetings_map.rb
config/application.rb
lib/extends/commands/decidim/admin/update_component_extends.rb
lib/extends/commands/decidim/assemblies/admin/update_assembly_extends.rb

This PR adds an override of decidim_geo to fix an error when updating a component  in the BO.
It overrides the file lib/decidim/geo/components/overrides/update_component_command_override.rb line 17 to add a false value if form.decidim_geo_avoid_index is nil
It also adds comments on other decidim_geo overrides to remember to delete them when the issues will be fixed on the module itself.
As an admin, go to a component in the BO and try to update it.
See that you don't have error.
Screen of the error

Fix: override decidim geo to fix component update

---

Gemfile.lock

This PR bumps the decidim-module-emitter to the latest version that removes the registration of the module as a component.
1. As an admin, go to a process
2. Click on Components, and then on "Add component"
3. See that emitter doesn't appear in the list of components
4. As an admin, go back to "About this process", add an emitter to check that it works as usual.
- Github card https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=118711068&issue=OpenSourcePolitics%7Cintern-tasks%7C57

feat: bump emitter 0.29 to latest version without component

---

Dockerfile

Add missing deface:precompile command to the dockerfile to avoid enabling it using `DEFACE_ENABLED=true` that may cause some issues
Example:
* Using docker setup your application
* Go to "Manage registration fields" make sure to enable it and to add some custom user fields.
* Using a private navigation make sure the custom registration has been changed
* Change an other time by adding or removing some fields
* Make sure it changed correctly
- Fixes #835

feat: Add deface precompile step to the Dockerfile

---

app/overrides/decidim/initiatives/admin/initiatives/_form/replace_condition_single_initiative.html.erb.deface

There was an issue when the initiative_type was unique, it didn't manage to get the scope and all following informations causing the initiative to be impossible to edit.
**You will need to access DB to delete every existing initiatives_types if you want to test it properly as three are already existing by default**
**You will need to run `bundle exec rake deface:precompile` to ensure the modifications are applied !**
Example:
* Go to initiatives
* Create a new initiative_type (make sure it is the only one existing)
* Create a new initiative on the front-office as a user
* Send it to technical validation
* Access back-office and try to edit your initiative
* Make sure everything works correctly
- Fixes #855

fix: Initiatives Edit if there is only one initiative_type

---

config/secrets.yml
spec/system/registration_spec.rb

This PR updates the value of admin_password expiration_days to 0, so that the admin password no longer expires.
1. As an admin, log in and see that you are not asked to change your password
2. Logout
3. Go to the rails console in your terminal with `bundle exec rails c`
4. Update the admin password_updated_at to a date superior to 90 days (which was the previous value for updating your password), with `Decidim::User.where(admin: true).first.update_column("password_updated_at", 200.days.ago)`
5. Check that the column has been updated with `Decidim::User.where(admin: true).first.password_updated_at`
6. Restart you rails server
7. Log in as admin and see that you are not asked to change your password, even if the password_updated_at value is superior to 90 days 
- Related to …

feat: remove admin expiration of password 

---

config/application.rb
lib/extends/cells/decidim/user_activity_cell_extends.rb
spec/cells/decidim/user_activity_cell_spec.rb

This PR removes deleted comments from public profile page.
1. As a logged_in user, add a comment to a proposal for instance.
2. Go to "My public profile" page and check in Activity that you see your comment (cf screenshot ONE).
3. Delete the comment added to the proposal
4. Go back to "My public profile" page and see that the deleted comment is not displayed (cf screenshot TWO).
- Github page https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=128913063&issue=OpenSourcePolitics%7Cdecidim-cdc%7C56
- Issue https://github.com/decidim/decidim/issues/15180
**ONE**
**TWO**

Fix deleted comments still on public profile

---

Gemfile.lock

This PR updates guest-meeting-registration module branch bump/0.29 to its latest commit to get missing fr translations for buttons.
As an admin, in the managing meeting's page, in the configure registration page, enable registration without a user account
Log out.
As a non logged-in user using fr language, in the FO, register to the meeting and see that the modal btns are translated in french.

bump: guest_meeting_registration module to have missing translations

---

.github/workflows/manual_release_from_branch.yml

Added a manual GitHub Actions workflow to create a release from a given branch.  
The workflow force-creates/moves the tag corresponding to the branch name and updates the associated release.
* Run the `Release from branch (manual)` workflow from the Actions tab
* Enter an existing branch (e.g., `develop` or `feature/add_banner`)
* Verify that a tag is created/updated with the branch name
* Verify that a GitHub release is created/updated
* Verify that the Docker image is pushed with this tag
The tag is recreated on each run and force-pushed to the latest commit of the target branch.

feat(github): add manual_release_from_branch.yml
